import "server-only";

import { LocalStorageAdapter } from "./local-storage-adapter";

/**
 * Storage abstraction (OD-42, ADR-0024). The application/domain layer never
 * imports `node:fs` or a cloud SDK directly — only this interface.
 *
 * `File.storageKey` (opaque, system-generated — see docs/domain/files.md) is
 * the only thing that crosses this boundary as a location; it is never a
 * user-controlled path. Every method must treat `key` as untyped-but-trusted
 * data generated by `@/features/files`, not as something to re-validate here.
 *
 * There is no `getAccessUrl` on this interface, unlike the illustrative shape
 * in some storage-abstraction write-ups. Studio's browser-facing file URLs are
 * always `/api/files/[fileId]` (the File's database id, not its storage key) —
 * that route re-checks department authorization on *every* request before
 * calling `readStream` here. A `getAccessUrl` that returned a storage-specific
 * URL would either leak the storage key to the client or require the adapter
 * to know about authorization, neither of which is this module's job. See
 * docs/architecture/files.md "Access & preview".
 */
export interface StorageObjectInfo {
  sizeBytes: number;
}

export interface StorageAdapter {
  /** Write `data` to `key`, creating or overwriting it. */
  put(key: string, data: Buffer): Promise<void>;
  /** Delete the object at `key`. Resolves even if it doesn't exist. */
  delete(key: string): Promise<void>;
  /** `null` if the object doesn't exist. */
  stat(key: string): Promise<StorageObjectInfo | null>;
  /**
   * A readable stream of the object's bytes, optionally a byte range
   * (`start`/`end` inclusive, as in an HTTP `Range` header) for partial
   * content responses (audio/video seeking).
   */
  readStream(
    key: string,
    range?: { start: number; end: number },
  ): NodeJS.ReadableStream;
}

/**
 * The active adapter. A single local-disk implementation today — see
 * `local-storage-adapter.ts` and ADR-0024 for why, and for what a future
 * S3-compatible adapter would need to change (nothing above this line).
 */
export const storage: StorageAdapter = new LocalStorageAdapter();
