import "server-only";

import { createReadStream } from "node:fs";
import { mkdir, open, rm, stat } from "node:fs/promises";
import path from "node:path";

import { env } from "@/server/env";
import { logger } from "@/server/logger";
import type { StorageAdapter, StorageObjectInfo } from "./index";

/**
 * Local filesystem storage adapter (ADR-0024). Suitable for development and a
 * single-instance deployment; swapping to an S3-compatible adapter later
 * means writing one new file behind `StorageAdapter` — nothing above it
 * changes (docs/architecture/files.md).
 *
 * `key` is always system-generated by `@/features/files` (never user input —
 * see the `StorageAdapter` doc comment), so path traversal isn't a realistic
 * attack surface here. `resolveKey` still refuses to resolve outside the
 * storage root as defense in depth (Security Requirements §8).
 */
export class LocalStorageAdapter implements StorageAdapter {
  private resolveKey(key: string): string {
    const root = path.resolve(process.cwd(), env.STORAGE_LOCAL_DIR);
    const resolved = path.resolve(root, key);
    if (resolved !== root && !resolved.startsWith(root + path.sep)) {
      // Should be unreachable — `key` never comes from user input.
      throw new Error(
        `Refusing to resolve storage key outside its root: ${key}`,
      );
    }
    return resolved;
  }

  async put(key: string, data: Buffer): Promise<void> {
    const filePath = this.resolveKey(key);
    await mkdir(path.dirname(filePath), { recursive: true });
    const handle = await open(filePath, "w");
    try {
      await handle.writeFile(data);
    } finally {
      await handle.close();
    }
  }

  async delete(key: string): Promise<void> {
    await rm(this.resolveKey(key), { force: true });
  }

  async stat(key: string): Promise<StorageObjectInfo | null> {
    try {
      const info = await stat(this.resolveKey(key));
      return { sizeBytes: info.size };
    } catch (error) {
      if (isNotFoundError(error)) return null;
      logger.error("Local storage stat failed", { key, cause: error });
      throw error;
    }
  }

  readStream(
    key: string,
    range?: { start: number; end: number },
  ): NodeJS.ReadableStream {
    return createReadStream(
      this.resolveKey(key),
      range ? { start: range.start, end: range.end } : undefined,
    );
  }
}

function isNotFoundError(error: unknown): boolean {
  return (
    typeof error === "object" &&
    error !== null &&
    "code" in error &&
    error.code === "ENOENT"
  );
}
